Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 16919
"GET /static/assets/css/theme.css HTTP/1.1" 304 0
"GET /static/assets/js/theme.js HTTP/1.1" 304 0
"GET /static/assets/js/theme.js HTTP/1.1" 200 3625
"GET /static/assets/js/scripts.bundle.js HTTP/1.1" 200 238050
"GET /static/assets/plugins/global/plugins.bundle.js HTTP/1.1" 200 3558077
"GET /theme/preference/ HTTP/1.1" 302 0
"GET /login/?next=/theme/preference/ HTTP/1.1" 200 9176
"GET /login/ HTTP/1.1" 200 9158
"POST /login/ HTTP/1.1" 302 0
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: core_communicationnotification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 155, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/context.py", line 259, in bind_template
    context = processor(self.request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/context_processors.py", line 14, in notifications_processor
    ).count()
      ~~~~~^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: core_communicationnotification
"GET /dashboard/ HTTP/1.1" 500 174663
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4185
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: core_communicationnotification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/context.py", line 259, in bind_template
    context = processor(self.request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/context_processors.py", line 14, in notifications_processor
    ).count()
      ~~~~~^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: core_communicationnotification
"GET / HTTP/1.1" 500 156178
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/models_notifications.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/models_notifications.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'core' is not a registered namespace
"GET / HTTP/1.1" 500 164896
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/meditrack/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/meditrack/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'notification-list' not found. 'notification-list' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 148826
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views_notification.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'notification-list' not found. 'notification-list' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 148826
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views_notification.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'notification-list' not found. 'notification-list' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 148826
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'notification-list' not found. 'notification-list' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 148190
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-list' not found. 'patient-list' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 162589
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views_notification.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-list' not found. 'patient-list' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 173124
"GET / HTTP/1.1" 200 30471
"GET /static/assets/plugins/global/fonts/@fortawesome/fa-solid-900.woff2 HTTP/1.1" 200 157192
"GET /theme/preference/ HTTP/1.1" 200 20
"POST /theme/toggle/ HTTP/1.1" 200 36
"POST /theme/toggle/ HTTP/1.1" 200 37
"POST /theme/toggle/ HTTP/1.1" 200 36
Internal Server Error: /treatments/medical-images/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-list' not found. 'patient-list' is not a valid view function or pattern name.
"GET /treatments/medical-images/ HTTP/1.1" 500 186187
Internal Server Error: /core/patients/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-detail' not found. 'patient-detail' is not a valid view function or pattern name.
"GET /core/patients/ HTTP/1.1" 500 178089
"GET /core/doctors/ HTTP/1.1" 200 31421
"GET /theme/preference/ HTTP/1.1" 200 19
Internal Server Error: /telemedicine/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: telemedicine/consultation_list.html, telemedicine/telemedicineconsultation_list.html
"GET /telemedicine/ HTTP/1.1" 500 84612
Internal Server Error: /treatments/medical-images/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-list' not found. 'patient-list' is not a valid view function or pattern name.
"GET /treatments/medical-images/ HTTP/1.1" 500 186187
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 156, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'appointment-list' not found. 'appointment-list' is not a valid view function or pattern name.
"GET /dashboard/ HTTP/1.1" 500 171784
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 156, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-detail' not found. 'patient-detail' is not a valid view function or pattern name.
"GET /dashboard/ HTTP/1.1" 500 199800
Internal Server Error: /appointments/calendar/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'appointment-create' not found. 'appointment-create' is not a valid view function or pattern name.
"GET /appointments/calendar/ HTTP/1.1" 500 171420
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 156, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-detail' not found. 'patient-detail' is not a valid view function or pattern name.
"GET /dashboard/ HTTP/1.1" 500 199800
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'url_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'url_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
unfold
unfold_list
"GET / HTTP/1.1" 500 210453
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'namespaced_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 92: 'namespaced_url', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 260526
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'namespaced_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 114: 'namespaced_url', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 221303
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'namespaced_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 132: 'namespaced_url', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 231146
"GET / HTTP/1.1" 200 30471
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /static/assets/media/logos/favicon.png HTTP/1.1" 304 0
Internal Server Error: /core/patients/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-detail' not found. 'patient-detail' is not a valid view function or pattern name.
"GET /core/patients/ HTTP/1.1" 500 178089
"GET /core/patients/ HTTP/1.1" 200 26335
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /core/doctors/ HTTP/1.1" 200 31421
"GET /theme/preference/ HTTP/1.1" 200 19
Internal Server Error: /core/appointments/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'appointment-create' not found. 'appointment-create' is not a valid view function or pattern name.
"GET /core/appointments/ HTTP/1.1" 500 172807
"GET /core/appointments/ HTTP/1.1" 200 29401
"GET /theme/preference/ HTTP/1.1" 200 19
Internal Server Error: /appointments/calendar/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'appointment-create' not found. 'appointment-create' is not a valid view function or pattern name.
"GET /appointments/calendar/ HTTP/1.1" 500 171438
"GET /appointments/calendar/ HTTP/1.1" 200 27054
"GET /theme/preference/ HTTP/1.1" 200 19
"POST /theme/toggle/ HTTP/1.1" 200 37
"POST /theme/toggle/ HTTP/1.1" 200 36
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/appointments/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /appointments/calendar/ HTTP/1.1" 200 27054
"GET /theme/preference/ HTTP/1.1" 200 19
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/appointments/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /core/doctors/ HTTP/1.1" 200 31421
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /core/patients/ HTTP/1.1" 200 26335
"GET /theme/preference/ HTTP/1.1" 200 19
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 156, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-detail' not found. 'patient-detail' is not a valid view function or pattern name.
"GET /dashboard/ HTTP/1.1" 500 199814
/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/appointments/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 156, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'patient-detail' not found. 'patient-detail' is not a valid view function or pattern name.
"GET /dashboard/ HTTP/1.1" 500 199951
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 156, in dashboard
    return render(request, 'core/doctor_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'treatment-detail' not found. 'treatment-detail' is not a valid view function or pattern name.
"GET /dashboard/ HTTP/1.1" 500 200709
"GET /dashboard/ HTTP/1.1" 200 29729
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /dashboard/ HTTP/1.1" 200 29729
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /core/patients/ HTTP/1.1" 200 26335
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /core/doctors/ HTTP/1.1" 200 31421
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /core/appointments/ HTTP/1.1" 200 29401
"GET /theme/preference/ HTTP/1.1" 200 19
"GET /appointments/calendar/ HTTP/1.1" 200 27054
"GET /theme/preference/ HTTP/1.1" 200 19
Internal Server Error: /telemedicine/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: telemedicine/consultation_list.html, telemedicine/telemedicineconsultation_list.html
"GET /telemedicine/ HTTP/1.1" 500 84634
Internal Server Error: /core/analytics/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 673, in analytics_dashboard
    return render(request, 'dashboards/analytics_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'analytics_data' not found. 'analytics_data' is not a valid view function or pattern name.
"GET /core/analytics/ HTTP/1.1" 500 196710
Internal Server Error: /core/analytics/
Traceback (most recent call last):
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/core/views.py", line 673, in analytics_dashboard
    return render(request, 'dashboards/analytics_dashboard.html', context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/umutaraz/Desktop/Tüm hayatım burda/MediTracked/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'analytics_data' not found. 'analytics_data' is not a valid view function or pattern name.
"GET /core/analytics/ HTTP/1.1" 500 196710
